---
branch_list:
  - tky
  - sng
  - hkg
role_list:
  - planning
  - banking
  - trading
  - sales
role_list_extra:
  - xva
openshift_project_name: tfy01
nfs_initial_path: tfy01-fors
production_tag_list:
  - official
  - stable
