---
- hosts: target_servers
  tasks:
  - name: create directory
    file:
      path: /tmp/work_ansible/test_dir
      state: directory
      owner: root
      mode: 0644

  - name: copy file
    copy:
      src: /etc/hosts
      dest: /tmp/work_ansible/test_dir/hosts
      owner: root
      mode: 0644
