---
- name: main | Manage outbound rules
  template:
    src: direct.xml.j2
    dest: /etc/firewalld/direct.xml
    owner: root
    group: root
    mode: '0644'
  when: firewall_enabled
  notify: "main | Restart firewalld"
  become: true
