---
## keycloak realm setting
- name: main | Create or update Keycloak realm
  community.general.keycloak_realm:
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_base_url }}"
    auth_realm: master
    auth_username: "{{ keycloak_auth_username }}"
    auth_password: "{{ keycloak_auth_password }}"
    id: "{{ keycloak_relalm_name }}"
    realm: "{{ keycloak_relalm_name }}"
    state: present
    login_theme: "{{ keycloak_login_theme }}"
    sso_session_idle_timeout: 86400
    sso_session_max_lifespan: 86400
    enabled: true
    validate_certs: false

## keycloak user federation setting
- name: main | Apply LDAP user federation
  community.general.keycloak_user_federation:
    auth_keycloak_url: "{{ keycloak_base_url }}"
    auth_realm: master
    auth_username: "{{ keycloak_auth_username }}"
    auth_password: "{{ keycloak_auth_password }}"
    realm: "{{ keycloak_relalm_name }}"
    name: freeipa
    state: present
    provider_id: ldap
    config:
      enabled: true
      # General option
      vendor: other
      # Connection and authentication settings
      connectionUrl: ldaps://ldap.example.com:636
      connectionPooling: false
      authType: simple
      bindDn: cn=directory reader
      bindCredential: password
      # LDAP searching and updating
      editMode: READ_ONLY
      usersDn: ou=Users,dc=example,dc=com
      usernameLDAPAttribute: uid
      rdnLDAPAttribute: uid
      uuidLDAPAttribute: entryDN
      userObjectClasses: inetOrgPerson, organizationalPerson
      pagination: false
      # Synchronization settings
      importEnabled: true
      # Kerberos integration
      # Cache settings
      # Advanced settings
    mappers:
      - name: "gidNumber"
        providerId: "user-attribute-ldap-mapper"
        providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
        config:
          ldap.attribute: "gidNumber"
          user.model.attribute: "gidNumber"
          read.only: false
      - name: "group"
        providerId: "group-ldap-mapper"
        providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
        config:
          groups.dn: "ou=Groups,dc=example,dc=com"
          preserve.group.inheritance: false
          mode: "LDAP_ONLY"
          mapped.group.attribute: "gidNumber"
    validate_certs: false

## keycloak identity provider setting
- name: main | Apply SAML identity provider
  community.general.keycloak_identity_provider:
    state: present
    auth_keycloak_url: "{{ keycloak_base_url }}"
    auth_realm: master
    auth_username: "{{ keycloak_auth_username }}"
    auth_password: "{{ keycloak_auth_password }}"
    realm: "{{ keycloak_relalm_name }}"
    alias: saml
    enabled: true
    provider_id: saml
    config:
      entityId: https://keycloak.example.com/realms/demo
      singleSignOnServiceUrl: https://login.microsoftonline.com/f3746012-9d9a-4731-a6d7-15491d2b7948/saml2
    validate_certs: false
