---
- name: main | Create or update Keycloak realm
  community.general.keycloak_realm:
    auth_client_id: admin-cli
    auth_keycloak_url: https://keycloak.example.com/auth
    auth_realm: master
    auth_username: admin
    auth_password: admin
    id: demo
    realm: demo_test
    state: present
    validate_certs: false
