---
- name: main | Create or update Keycloak realm
  community.general.keycloak_realm:
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_base_url }}"
    auth_realm: master
    auth_username: admin
    auth_password: admin
    id: "{{ keycloak_relalm_name }}"
    realm: "{{ keycloak_relalm_name }}"
    state: present
    login_theme: "{{ keycloak_login_theme }}"
    sso_session_idle_timeout: 86400
    sso_session_max_lifespan: 86400
    validate_certs: false
