---
- name: main | Install python
  dnf:
    name: "{{ python_package }}"
    state: installed
  become: true

- name: main | Install python dependencies package
  pip:
    name: "{{ python_dependencies_package }}"
    executable: pip3.8
  become: true

- name: main | Deploy python symbolic link
  file:
    src: "{{ shell_dir }}/python3"
    dest: "{{ shell_dir }}/python"
    state: link
  become: true

- name: main | Deploy pip symbolic link
  file:
    src: "{{ shell_dir }}/pip3"
    dest: "{{ shell_dir }}/pip"
    state: link
  become: true
