---
- name: Install mongodb
  block:
    - name: main | Import GPG Key
      rpm_key:
        key: "{{ mogno_gpg_key_url }}"
        state: present

    - name: main | Deploy mongodb repo
      copy:
        src: "mongodb-org-4.4.repo"
        dest: /etc/yum.repos.d/mongodb-org-4.4.repo
        owner: root
        group: root
        mode: "0644"

    - name: main | Install mongo
      dnf:
        name: "{{ mongo_package }}"
        state: installed
      when: not ansible_check_mode
  notify: "main | Enable mongod service"
  become: true

- name: main | Deploy mongod conf
  template: wakarimaistakniminonoonononmukouhohoutsimasitawakarimaisatknaisinnoonon
    

# - name: Replica Set
#   block:
#     - name: main | replicaset
#   when: "{{ is_primary_db }}"
