---
- name: Install mongodb
  block:
    - name: main | Import GPG Key
      rpm_key:
        key: "{{ mogno_gpg_key_url }}"
        state: present

    - name: main | Deploy mongodb repo
      copy:
        src: "mongodb-org-4.4.repo"
        dest: /etc/yum.repos.d/mongodb-org-4.4.repo
        owner: root
        group: root
        mode: "0644"

    - name: main | Install mongo
      dnf:
        name: "{{ mongo_package }}"
        state: installed
      when: not ansible_check_mode
  become: true

- name: main | Deploy mongod conf
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: "0644"
  notify: "main | Restart mongod service"
  become: true
    
- name: main | Replica Set
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: admin
    login_password: {{ mongo_admin_password }}
    replica_set: rs0
    members:
    - host: "{{ mongodb_primary_host }}"
      priority: 1
    - host: "{{ mongodb_secondary_host }}"
      priority: 0
    - host: "{{ mongodb_arbiter_host }}"
      priority: 0
    arbiter_at_index: 2
  when: mongo_admin_password is defined
  become: true
